"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
exports.__esModule = true;
var styled_components_1 = require("styled-components");
var react_table_1 = require("./react-table");
var react_table_hoc_fixed_columns_1 = require("./react-table-hoc-fixed-columns");
exports["default"] = styled_components_1["default"].div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  /* React table style customization */\n  width: 100%;\n\n  .ReactTable .rt-thead.-header .rt-th {\n    color: ", ";\n    background-color: ", ";\n  }\n  .ReactTable.-striped .rt-tr.-odd > div {\n    color: ", ";\n    background-color: ", ";\n  }\n\n  .ReactTable.-striped .rt-tr.-even > div {\n    color: ", ";\n    background-color: ", ";\n  }\n\n  .ReactTable.-highlight .rt-tbody .rt-tr:not(.-padRow):hover {\n    /* \n    What does this selector do? \n    These classes were in our react-table style sheet previously\n    color: var(--theme-app-fg);\n    background: var(--cm-background); \n    */\n  }\n\n  .ReactTable .-pagination .-btn {\n  }\n\n  /* \n  These parts are mostly copied from the dependency packages, \n  but we remove some things that clash with us\n  */\n  ", "\n  ", "\n"], ["\n  /* React table style customization */\n  width: 100%;\n\n  .ReactTable .rt-thead.-header .rt-th {\n    color: ", ";\n    background-color: ", ";\n  }\n  .ReactTable.-striped .rt-tr.-odd > div {\n    color: ", ";\n    background-color: ", ";\n  }\n\n  .ReactTable.-striped .rt-tr.-even > div {\n    color: ", ";\n    background-color: ", ";\n  }\n\n  .ReactTable.-highlight .rt-tbody .rt-tr:not(.-padRow):hover {\n    /* \n    What does this selector do? \n    These classes were in our react-table style sheet previously\n    color: var(--theme-app-fg);\n    background: var(--cm-background); \n    */\n  }\n\n  .ReactTable .-pagination .-btn {\n  }\n\n  /* \n  These parts are mostly copied from the dependency packages, \n  but we remove some things that clash with us\n  */\n  ", "\n  ", "\n"])), function (props) { return (props.theme === "dark" ? "#bbb" : "#111"); }, function (props) { return (props.theme === "dark" ? "#1e1e1e" : "#fff"); }, function (props) { return (props.theme === "dark" ? "#bbb" : "#111"); }, function (props) { return (props.theme === "dark" ? "#1e1e1e" : "#fff"); }, function (props) { return (props.theme === "dark" ? "#bbb" : "#111"); }, function (props) { return (props.theme === "dark" ? "#111" : "#f7f7f7"); }, react_table_1["default"], react_table_hoc_fixed_columns_1["default"]);
var templateObject_1;
